name: Update ECB Data

on:
  schedule:
    - cron: "0 5 * * *"  # Daily at 05:00 UTC (6 AM CET during winter)
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("ecb", "data.table", "magrittr", "readr", "here", "xts"))'

      - name: Run the update script
        run: Rscript update_data.R

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.rds
          git commit -m "Daily data update"
          git push
